'use strict';

export const APPLICATION_USER_ISACCESSTOKEN_BEGIN     = 'APPLICATION_USER_ISACCESSTOKEN_BEGIN'
export const APPLICATION_USER_ISACCESSTOKEN_FAILURE   = 'APPLICATION_USER_ISACCESSTOKEN_FAILURE'
export const APPLICATION_USER_ISACCESSTOKEN_SUCCESS   = 'APPLICATION_USER_ISACCESSTOKEN_SUCCESS'

export const APPLICATION_USER_LOGIN_BEGIN             = 'APPLICATION_USER_LOGIN_BEGIN'
export const APPLICATION_USER_LOGIN_FAILURE           = 'APPLICATION_USER_LOGIN_FAILURE'
export const APPLICATION_USER_LOGIN_SUCCESS           = 'APPLICATION_USER_LOGIN_SUCCESS'

export const APPLICATION_USER_REGISTER_BEGIN          = 'APPLICATION_USER_REGISTER_BEGIN'
export const APPLICATION_USER_REGISTER_FAILURE        = 'APPLICATION_USER_REGISTER_FAILURE'
export const APPLICATION_USER_REGISTER_SUCCESS        = 'APPLICATION_USER_REGISTER_SUCCESS'