'use strict';

export const APPLICATION_USER_ISACCESSTOKEN_BEGIN     = 'APPLICATION_USER_ISACCESSTOKEN_BEGIN'
export const APPLICATION_USER_ISACCESSTOKEN_FAILURE   = 'APPLICATION_USER_ISACCESSTOKEN_FAILURE'
export const APPLICATION_USER_ISACCESSTOKEN_SUCCESS   = 'APPLICATION_USER_ISACCESSTOKEN_SUCCESS'