'use strict';

export const CLASSIFY_BOOK_LIST_BEGIN           = 'CLASSIFY_BOOK_LIST_BEGIN'
export const CLASSIFY_BOOK_LIST_FAILURE         = 'CLASSIFY_BOOK_LIST_FAILURE'
export const CLASSIFY_BOOK_LIST_SUCCESS         = 'CLASSIFY_BOOK_LIST_SUCCESS'