'use strict';

export const RECOMMEND_BOOK_LIST_BEGIN           = 'RECOMMEND_BOOK_LIST_BEGIN'
export const RECOMMEND_BOOK_LIST_FAILURE         = 'RECOMMEND_BOOK_LIST_FAILURE'
export const RECOMMEND_BOOK_LIST_SUCCESS         = 'RECOMMEND_BOOK_LIST_SUCCESS'