'use strict';

export const HOME_CLASSIFY_LIST_BEGIN     = 'HOME_CLASSIFY_LIST_BEGIN'
export const HOME_CLASSIFY_LIST_FAILURE   = 'HOME_CLASSIFY_LIST_FAILURE'
export const HOME_CLASSIFY_LIST_SUCCESS   = 'HOME_CLASSIFY_LIST_SUCCESS'
export const HOME_DEFAULT_INFO_BEGIN      = 'HOME_DEFAULT_INFO_BEGIN'
export const HOME_DEFAULT_INFO_FAILURE    = 'HOME_DEFAULT_INFO_FAILURE'
export const HOME_DEFAULT_INFO_SUCCESS    = 'HOME_DEFAULT_INFO_SUCCESS'
export const HOME_TIAOMAN_INFO_BEGIN      = 'HOME_TIAOMAN_INFO_BEGIN'
export const HOME_TIAOMAN_INFO_FAILURE    = 'HOME_TIAOMAN_INFO_FAILURE'
export const HOME_TIAOMAN_INFO_SUCCESS    = 'HOME_TIAOMAN_INFO_SUCCESS'