'use strict';

export const SHELF_COLLECT_LIST_BEGIN     = 'SHELF_COLLECT_LIST_BEGIN'
export const SHELF_COLLECT_LIST_FAILURE   = 'SHELF_COLLECT_LIST_FAILURE'
export const SHELF_COLLECT_LIST_SUCCESS   = 'SHELF_COLLECT_LIST_SUCCESS'
export const SHELF_READREC_LIST_BEGIN     = 'SHELF_READREC_LIST_BEGIN'
export const SHELF_READREC_LIST_FAILURE   = 'SHELF_READREC_LIST_FAILURE'
export const SHELF_READREC_LIST_SUCCESS   = 'SHELF_READREC_LIST_SUCCESS'

export const SHELF_MENU_EDITMODE_OPEN     = 'SHELF_MENU_EDITMODE_OPEN'
export const SHELF_MENU_EDITMODE_INIT     = 'SHELF_MENU_EDITMODE_INIT'
export const SHELF_MENU_EDITMODE_SELECT   = 'SHELF_MENU_EDITMODE_SELECT'
export const SHELF_MENU_EDITMODE_REMOVE   = 'SHELF_MENU_EDITMODE_REMOVE'