'use strict';

export const SHELF_COLLECT_LIST_BEGIN        = 'SHELF_COLLECT_LIST_BEGIN'
export const SHELF_COLLECT_LIST_FAILURE      = 'SHELF_COLLECT_LIST_FAILURE'
export const SHELF_COLLECT_LIST_SUCCESS      = 'SHELF_COLLECT_LIST_SUCCESS'
export const SHELF_READREC_LIST_BEGIN        = 'SHELF_READREC_LIST_BEGIN'
export const SHELF_READREC_LIST_FAILURE      = 'SHELF_READREC_LIST_FAILURE'
export const SHELF_READREC_LIST_SUCCESS      = 'SHELF_READREC_LIST_SUCCESS'

export const SHELF_MENU_EDITMODE_OPEN        = 'SHELF_MENU_EDITMODE_OPEN'
export const SHELF_MENU_EDITMODE_INIT        = 'SHELF_MENU_EDITMODE_INIT'
export const SHELF_MENU_EDITMODE_SELECT      = 'SHELF_MENU_EDITMODE_SELECT'
//export const SHELF_MENU_EDITMODE_REMOVE      = 'SHELF_MENU_EDITMODE_REMOVE'

export const SHELF_MENU_EDITMODE_REMOVE_BEGIN = 'SHELF_MENU_EDITMODE_REMOVE_BEGIN'
export const SHELF_MENU_EDITMODE_REMOVE_FAILURE = 'SHELF_MENU_EDITMODE_REMOVE_FAILURE'
export const SHELF_MENU_EDITMODE_REMOVE_SUCCESS = 'SHELF_MENU_EDITMODE_REMOVE_SUCCESS'

export const SHELF_COLLECT_ADD_BEGIN         = 'SHELF_COLLECT_ADD_BEGIN'
export const SHELF_COLLECT_ADD_FAILURE       = 'SHELF_COLLECT_ADD_FAILURE'
export const SHELF_COLLECT_ADD_SUCCESS       = 'SHELF_COLLECT_ADD_SUCCESS'
export const SHELF_COLLECT_REMOVE_BEGIN      = 'SHELF_COLLECT_REMOVE_BEGIN'
export const SHELF_COLLECT_REMOVE_FAILURE    = 'SHELF_COLLECT_REMOVE_FAILURE'
export const SHELF_COLLECT_REMOVE_SUCCESS    = 'SHELF_COLLECT_REMOVE_SUCCESS'
export const SHELF_INIT_COLLECT_BOOK         = 'SHELF_INIT_COLLECT_BOOK'

export const SHELF_READREC_UPDATE_BEGIN         = 'SHELF_READREC_UPDATE_BEGIN'
export const SHELF_READREC_UPDATE_FAILURE       = 'SHELF_READREC_UPDATE_FAILURE'
export const SHELF_READREC_UPDATE_SUCCESS       = 'SHELF_READREC_UPDATE_SUCCESS'