'use strict';

export const SEARCH_BOOK_LIST_BEGIN           = 'SEARCH_BOOK_LIST_BEGIN'
export const SEARCH_BOOK_LIST_FAILURE         = 'SEARCH_BOOK_LIST_FAILURE'
export const SEARCH_BOOK_LIST_SUCCESS         = 'SEARCH_BOOK_LIST_SUCCESS'
export const SEARCH_BOOK_LIST_CLEAR           = 'SEARCH_BOOK_LIST_CLEAR'
export const SEARCH_BOOK_LIST_HISTORY_CLEAR   = 'SEARCH_BOOK_LIST_HISTORY_CLEAR'